baseurl = "https://dev.pippi.im/"
languageCode = "en-us"
title = "/dev/ by Massimiliano Pippi"
pygmentsstyle = "manni"
googleAnalytics = "UA-43125807-1"
theme = "m10c"

[params]
AuthorName = "Massimiliano Pippi"
Avatar = "images/massi.png"
Description = """Massi here. Software developer, engineering manager, I can ops.
    Open source advocate and contributor, documentation fanatic, speaker at conferences.
    I wrote a book once."""

# Social Icons
[[params.social]]
name = "github"
url = "https://github.com/masci"
[[params.social]]
name = "linkedin"
url = "http://www.linkedin.com/in/masci"

# Active projects
[[params.active_project]]
name = "Intro to Kubernetes"
url = "https://masci.github.io/k8s101/"
description = "A 2-hours workshop to go from zero to Kubernetes"
[[params.active_project]]
name = "actions/datadog"
url = "https://github.com/masci/datadog"
description = "Send Datadog metrics and events from GitHub workflows"
[[params.active_project]]
name = "drone-datadog"
url = "https://github.com/masci/drone-datadog"
description = "A drone.io plugin to send events and metrics to Datadog"
[[params.active_project]]
name = "Threadle"
url = "https://github.com/masci/threadle"
description = "Ingest metrics from a Datadog Agent and send them to a custom storage using different plugins"
[[params.active_project]]
name = "actions/elastic-logs"
url = "https://github.com/masci/elastic-logs"
description = "Fetch logs from GitHub workflows and ingest them to Elasticsearch"