name = "/dev/"
license = "MIT"
source_repo = ""
description = "Based on Readable by Bootswatch"
tags = ["blog", "company"]
features = ["blog", ]

[author]
    name = "masci"
    email = "mpippi@gmail.com"
    url = "http://dev.pippi.im"

[original]
    author =  "Bootswatch"
    url = "http://bootswatch.com"
    repo = ""
